name: PR
on:
  pull_request:
  workflow_dispatch:
jobs:
  Fix:
    runs-on: ubuntu-latest
    outputs:
      ref: ${{ steps.commit.outputs.commit_hash || github.ref }}
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, bcmath, intl, gd, exif, iconv, fileinfo
      - run: composer install
      - run: vendor/bin/pint
      - id: commit
        uses: stefanzweifel/git-auto-commit-action@v5
  Test:
    needs: [Fix]
    uses: ./.github/workflows/test.yml
    with:
      ref: ${{ needs.Fix.outputs.ref }}
